#ifndef __OPENHWGROUP_CVWSOC_COMMON_CONFIG_H
#define __OPENHWGROUP_CVWSOC_COMMON_CONFIG_H

#include <linux/sizes.h>

#define CFG_SYS_SDRAM_BASE		0x80000000
#define CONFIG_SYS_INIT_SP_ADDR		(CFG_SYS_SDRAM_BASE + SZ_2M)

#endif
